name: Emily Stacy
description: Engineering | Learning Science | Data/AI
avatar: https://github.com/EmilyStacy-droid.png # This automatically pulls your GH profile pic

footer-links:
  github: EmilyStacy-droid
  linkedin: jinglanstacy # Add your actual username here
  email: emilystacy2020@gmail.com

# This tells Jekyll to use a clean theme and ignore the blog stuff
theme: jekyll-theme-minimal